// Copyright 2023 Samvaad, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: samvaad_agent_dispatch.proto

package samvaad

import (
	_ "github.com/msmclass/samvaad/pkg/proto/samvaad/logger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRestartPolicy int32

const (
	JobRestartPolicy_JRP_ON_FAILURE JobRestartPolicy = 0 // restart when the job fails (default)
	JobRestartPolicy_JRP_NEVER      JobRestartPolicy = 1 // never restart
)

// Enum value maps for JobRestartPolicy.
var (
	JobRestartPolicy_name = map[int32]string{
		0: "JRP_ON_FAILURE",
		1: "JRP_NEVER",
	}
	JobRestartPolicy_value = map[string]int32{
		"JRP_ON_FAILURE": 0,
		"JRP_NEVER":      1,
	}
)

func (x JobRestartPolicy) Enum() *JobRestartPolicy {
	p := new(JobRestartPolicy)
	*p = x
	return p
}

func (x JobRestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobRestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_samvaad_agent_dispatch_proto_enumTypes[0].Descriptor()
}

func (JobRestartPolicy) Type() protoreflect.EnumType {
	return &file_samvaad_agent_dispatch_proto_enumTypes[0]
}

func (x JobRestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobRestartPolicy.Descriptor instead.
func (JobRestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{0}
}

type CreateAgentDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RestartPolicy JobRestartPolicy       `protobuf:"varint,4,opt,name=restart_policy,json=restartPolicy,proto3,enum=samvaad.JobRestartPolicy" json:"restart_policy,omitempty"` // cloud only
	Deployment    string                 `protobuf:"bytes,5,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentDispatchRequest) Reset() {
	*x = CreateAgentDispatchRequest{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentDispatchRequest) ProtoMessage() {}

func (x *CreateAgentDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentDispatchRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentDispatchRequest) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentDispatchRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *CreateAgentDispatchRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CreateAgentDispatchRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CreateAgentDispatchRequest) GetRestartPolicy() JobRestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return JobRestartPolicy_JRP_ON_FAILURE
}

func (x *CreateAgentDispatchRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type RoomAgentDispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RestartPolicy JobRestartPolicy       `protobuf:"varint,3,opt,name=restart_policy,json=restartPolicy,proto3,enum=samvaad.JobRestartPolicy" json:"restart_policy,omitempty"` // cloud only
	Deployment    string                 `protobuf:"bytes,4,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomAgentDispatch) Reset() {
	*x = RoomAgentDispatch{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomAgentDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAgentDispatch) ProtoMessage() {}

func (x *RoomAgentDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAgentDispatch.ProtoReflect.Descriptor instead.
func (*RoomAgentDispatch) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *RoomAgentDispatch) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *RoomAgentDispatch) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *RoomAgentDispatch) GetRestartPolicy() JobRestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return JobRestartPolicy_JRP_ON_FAILURE
}

func (x *RoomAgentDispatch) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type DeleteAgentDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispatchId    string                 `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentDispatchRequest) Reset() {
	*x = DeleteAgentDispatchRequest{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentDispatchRequest) ProtoMessage() {}

func (x *DeleteAgentDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentDispatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentDispatchRequest) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAgentDispatchRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *DeleteAgentDispatchRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type ListAgentDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispatchId    string                 `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"` // if set, only the dispatch whose id is given will be returned
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                               // name of the room to list agents for. Must be set.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentDispatchRequest) Reset() {
	*x = ListAgentDispatchRequest{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentDispatchRequest) ProtoMessage() {}

func (x *ListAgentDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentDispatchRequest.ProtoReflect.Descriptor instead.
func (*ListAgentDispatchRequest) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentDispatchRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *ListAgentDispatchRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type ListAgentDispatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentDispatches []*AgentDispatch       `protobuf:"bytes,1,rep,name=agent_dispatches,json=agentDispatches,proto3" json:"agent_dispatches,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAgentDispatchResponse) Reset() {
	*x = ListAgentDispatchResponse{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentDispatchResponse) ProtoMessage() {}

func (x *ListAgentDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentDispatchResponse.ProtoReflect.Descriptor instead.
func (*ListAgentDispatchResponse) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentDispatchResponse) GetAgentDispatches() []*AgentDispatch {
	if x != nil {
		return x.AgentDispatches
	}
	return nil
}

type AgentDispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	State         *AgentDispatchState    `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	RestartPolicy JobRestartPolicy       `protobuf:"varint,6,opt,name=restart_policy,json=restartPolicy,proto3,enum=samvaad.JobRestartPolicy" json:"restart_policy,omitempty"` // cloud only
	Deployment    string                 `protobuf:"bytes,7,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDispatch) Reset() {
	*x = AgentDispatch{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDispatch) ProtoMessage() {}

func (x *AgentDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDispatch.ProtoReflect.Descriptor instead.
func (*AgentDispatch) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{5}
}

func (x *AgentDispatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDispatch) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentDispatch) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentDispatch) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AgentDispatch) GetState() *AgentDispatchState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *AgentDispatch) GetRestartPolicy() JobRestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return JobRestartPolicy_JRP_ON_FAILURE
}

func (x *AgentDispatch) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type AgentDispatchState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For dispatches of tyoe JT_ROOM, there will be at most 1 job.
	// For dispatches of type JT_PUBLISHER, there will be 1 per publisher.
	Jobs          []*Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	CreatedAt     int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     int64  `protobuf:"varint,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDispatchState) Reset() {
	*x = AgentDispatchState{}
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDispatchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDispatchState) ProtoMessage() {}

func (x *AgentDispatchState) ProtoReflect() protoreflect.Message {
	mi := &file_samvaad_agent_dispatch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDispatchState.ProtoReflect.Descriptor instead.
func (*AgentDispatchState) Descriptor() ([]byte, []int) {
	return file_samvaad_agent_dispatch_proto_rawDescGZIP(), []int{6}
}

func (x *AgentDispatchState) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *AgentDispatchState) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AgentDispatchState) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

var File_samvaad_agent_dispatch_proto protoreflect.FileDescriptor

const file_samvaad_agent_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x1c\x6c\x69\x76\x65\x6b\x69\x74_agent_dispatch.proto\x12\a\x6c\x69\x76\x65\x6b\x69\x74\x1a\x13\x6c\x69\x76\x65\x6b\x69\x74_agent.proto\x1a\x14logger/options.proto\"\xd2\x01\n" +
	"\x1aCreateAgentDispatchRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x1f\n" +
	"\bmetadata\x18\x03 \x01(\tB\x03\xa8P\x01R\bmetadata\x12@\n" +
	"\x0erestart_policy\x18\x04 \x01(\x0e2\x19.\x6c\x69\x76\x65\x6b\x69\x74.JobRestartPolicyR\rrestartPolicy\x12\x1e\n" +
	"\n" +
	"deployment\x18\x05 \x01(\tR\n" +
	"deployment\"\xb5\x01\n" +
	"\x11RoomAgentDispatch\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1f\n" +
	"\bmetadata\x18\x02 \x01(\tB\x03\xa8P\x01R\bmetadata\x12@\n" +
	"\x0erestart_policy\x18\x03 \x01(\x0e2\x19.\x6c\x69\x76\x65\x6b\x69\x74.JobRestartPolicyR\rrestartPolicy\x12\x1e\n" +
	"\n" +
	"deployment\x18\x04 \x01(\tR\n" +
	"deployment\"`\n" +
	"\x1aDeleteAgentDispatchRequest\x12.\n" +
	"\vdispatch_id\x18\x01 \x01(\tB\r\xbaP\n" +
	"dispatchIDR\n" +
	"dispatchId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"^\n" +
	"\x18ListAgentDispatchRequest\x12.\n" +
	"\vdispatch_id\x18\x01 \x01(\tB\r\xbaP\n" +
	"dispatchIDR\n" +
	"dispatchId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"^\n" +
	"\x19ListAgentDispatchResponse\x12A\n" +
	"\x10agent_dispatches\x18\x01 \x03(\v2\x16.\x6c\x69\x76\x65\x6b\x69\x74.AgentDispatchR\x0fagentDispatches\"\x88\x02\n" +
	"\rAgentDispatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x1f\n" +
	"\bmetadata\x18\x04 \x01(\tB\x03\xa8P\x01R\bmetadata\x121\n" +
	"\x05state\x18\x05 \x01(\v2\x1b.\x6c\x69\x76\x65\x6b\x69\x74.AgentDispatchStateR\x05state\x12@\n" +
	"\x0erestart_policy\x18\x06 \x01(\x0e2\x19.\x6c\x69\x76\x65\x6b\x69\x74.JobRestartPolicyR\rrestartPolicy\x12\x1e\n" +
	"\n" +
	"deployment\x18\a \x01(\tR\n" +
	"deployment\"t\n" +
	"\x12AgentDispatchState\x12 \n" +
	"\x04jobs\x18\x01 \x03(\v2\f.\x6c\x69\x76\x65\x6b\x69\x74.JobR\x04jobs\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\x03R\tdeletedAt*5\n" +
	"\x10JobRestartPolicy\x12\x12\n" +
	"\x0eJRP_ON_FAILURE\x10\x00\x12\r\n" +
	"\tJRP_NEVER\x10\x012\x8b\x02\n" +
	"\x14AgentDispatchService\x12M\n" +
	"\x0eCreateDispatch\x12#.\x6c\x69\x76\x65\x6b\x69\x74.CreateAgentDispatchRequest\x1a\x16.\x6c\x69\x76\x65\x6b\x69\x74.AgentDispatch\x12M\n" +
	"\x0eDeleteDispatch\x12#.\x6c\x69\x76\x65\x6b\x69\x74.DeleteAgentDispatchRequest\x1a\x16.\x6c\x69\x76\x65\x6b\x69\x74.AgentDispatch\x12U\n" +
	"\fListDispatch\x12!.\x6c\x69\x76\x65\x6b\x69\x74.ListAgentDispatchRequest\x1a\".\x6c\x69\x76\x65\x6b\x69\x74.ListAgentDispatchResponseBFZ#github.com/\x6c\x69\x76\x65\x6b\x69\x74/protocol/\x6c\x69\x76\x65\x6b\x69\x74\xaa\x02\r\x4c\x69\x76\x65\x4b\x69\x74.Proto\xea\x02\x0e\x4c\x69\x76\x65\x4b\x69\x74::Protob\x06proto3"

var (
	file_samvaad_agent_dispatch_proto_rawDescOnce sync.Once
	file_samvaad_agent_dispatch_proto_rawDescData []byte
)

func file_samvaad_agent_dispatch_proto_rawDescGZIP() []byte {
	file_samvaad_agent_dispatch_proto_rawDescOnce.Do(func() {
		file_samvaad_agent_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_samvaad_agent_dispatch_proto_rawDesc), len(file_samvaad_agent_dispatch_proto_rawDesc)))
	})
	return file_samvaad_agent_dispatch_proto_rawDescData
}

var file_samvaad_agent_dispatch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_samvaad_agent_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_samvaad_agent_dispatch_proto_goTypes = []any{
	(JobRestartPolicy)(0),              // 0: samvaad.JobRestartPolicy
	(*CreateAgentDispatchRequest)(nil), // 1: samvaad.CreateAgentDispatchRequest
	(*RoomAgentDispatch)(nil),          // 2: samvaad.RoomAgentDispatch
	(*DeleteAgentDispatchRequest)(nil), // 3: samvaad.DeleteAgentDispatchRequest
	(*ListAgentDispatchRequest)(nil),   // 4: samvaad.ListAgentDispatchRequest
	(*ListAgentDispatchResponse)(nil),  // 5: samvaad.ListAgentDispatchResponse
	(*AgentDispatch)(nil),              // 6: samvaad.AgentDispatch
	(*AgentDispatchState)(nil),         // 7: samvaad.AgentDispatchState
	(*Job)(nil),                        // 8: samvaad.Job
}
var file_samvaad_agent_dispatch_proto_depIdxs = []int32{
	0, // 0: samvaad.CreateAgentDispatchRequest.restart_policy:type_name -> samvaad.JobRestartPolicy
	0, // 1: samvaad.RoomAgentDispatch.restart_policy:type_name -> samvaad.JobRestartPolicy
	6, // 2: samvaad.ListAgentDispatchResponse.agent_dispatches:type_name -> samvaad.AgentDispatch
	7, // 3: samvaad.AgentDispatch.state:type_name -> samvaad.AgentDispatchState
	0, // 4: samvaad.AgentDispatch.restart_policy:type_name -> samvaad.JobRestartPolicy
	8, // 5: samvaad.AgentDispatchState.jobs:type_name -> samvaad.Job
	1, // 6: samvaad.AgentDispatchService.CreateDispatch:input_type -> samvaad.CreateAgentDispatchRequest
	3, // 7: samvaad.AgentDispatchService.DeleteDispatch:input_type -> samvaad.DeleteAgentDispatchRequest
	4, // 8: samvaad.AgentDispatchService.ListDispatch:input_type -> samvaad.ListAgentDispatchRequest
	6, // 9: samvaad.AgentDispatchService.CreateDispatch:output_type -> samvaad.AgentDispatch
	6, // 10: samvaad.AgentDispatchService.DeleteDispatch:output_type -> samvaad.AgentDispatch
	5, // 11: samvaad.AgentDispatchService.ListDispatch:output_type -> samvaad.ListAgentDispatchResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_samvaad_agent_dispatch_proto_init() }
func file_samvaad_agent_dispatch_proto_init() {
	if File_samvaad_agent_dispatch_proto != nil {
		return
	}
	file_samvaad_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_samvaad_agent_dispatch_proto_rawDesc), len(file_samvaad_agent_dispatch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_samvaad_agent_dispatch_proto_goTypes,
		DependencyIndexes: file_samvaad_agent_dispatch_proto_depIdxs,
		EnumInfos:         file_samvaad_agent_dispatch_proto_enumTypes,
		MessageInfos:      file_samvaad_agent_dispatch_proto_msgTypes,
	}.Build()
	File_samvaad_agent_dispatch_proto = out.File
	file_samvaad_agent_dispatch_proto_goTypes = nil
	file_samvaad_agent_dispatch_proto_depIdxs = nil
}
