// Copyright 2025 Samvaad, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: samvaad_connector.proto

package samvaad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectorType int32

const (
	ConnectorType_Unspecified ConnectorType = 0
	ConnectorType_WhatsApp    ConnectorType = 1
	ConnectorType_Twilio      ConnectorType = 2
)

// Enum value maps for ConnectorType.
var (
	ConnectorType_name = map[int32]string{
		0: "Unspecified",
		1: "WhatsApp",
		2: "Twilio",
	}
	ConnectorType_value = map[string]int32{
		"Unspecified": 0,
		"WhatsApp":    1,
		"Twilio":      2,
	}
)

func (x ConnectorType) Enum() *ConnectorType {
	p := new(ConnectorType)
	*p = x
	return p
}

func (x ConnectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_samvaad_connector_proto_enumTypes[0].Descriptor()
}

func (ConnectorType) Type() protoreflect.EnumType {
	return &file_samvaad_connector_proto_enumTypes[0]
}

func (x ConnectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectorType.Descriptor instead.
func (ConnectorType) EnumDescriptor() ([]byte, []int) {
	return file_samvaad_connector_proto_rawDescGZIP(), []int{0}
}

var File_samvaad_connector_proto protoreflect.FileDescriptor

const file_samvaad_connector_proto_rawDesc = "" +
	"\n" +
	"\x17\x6c\x69\x76\x65\x6b\x69\x74_connector.proto\x12\a\x6c\x69\x76\x65\x6b\x69\x74\x1a \x6c\x69\x76\x65\x6b\x69\x74_connector_whatsapp.proto\x1a\x1e\x6c\x69\x76\x65\x6b\x69\x74_connector_twilio.proto*:\n" +
	"\rConnectorType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\f\n" +
	"\bWhatsApp\x10\x01\x12\n" +
	"\n" +
	"\x06Twilio\x10\x022\xec\x03\n" +
	"\tConnector\x12W\n" +
	"\x10DialWhatsAppCall\x12 .\x6c\x69\x76\x65\x6b\x69\x74.DialWhatsAppCallRequest\x1a!.\x6c\x69\x76\x65\x6b\x69\x74.DialWhatsAppCallResponse\x12i\n" +
	"\x16DisconnectWhatsAppCall\x12&.\x6c\x69\x76\x65\x6b\x69\x74.DisconnectWhatsAppCallRequest\x1a'.\x6c\x69\x76\x65\x6b\x69\x74.DisconnectWhatsAppCallResponse\x12`\n" +
	"\x13ConnectWhatsAppCall\x12#.\x6c\x69\x76\x65\x6b\x69\x74.ConnectWhatsAppCallRequest\x1a$.\x6c\x69\x76\x65\x6b\x69\x74.ConnectWhatsAppCallResponse\x12]\n" +
	"\x12AcceptWhatsAppCall\x12\".\x6c\x69\x76\x65\x6b\x69\x74.AcceptWhatsAppCallRequest\x1a#.\x6c\x69\x76\x65\x6b\x69\x74.AcceptWhatsAppCallResponse\x12Z\n" +
	"\x11ConnectTwilioCall\x12!.\x6c\x69\x76\x65\x6b\x69\x74.ConnectTwilioCallRequest\x1a\".\x6c\x69\x76\x65\x6b\x69\x74.ConnectTwilioCallResponseBFZ#github.com/\x6c\x69\x76\x65\x6b\x69\x74/protocol/\x6c\x69\x76\x65\x6b\x69\x74\xaa\x02\r\x4c\x69\x76\x65\x4b\x69\x74.Proto\xea\x02\x0e\x4c\x69\x76\x65\x4b\x69\x74::Protob\x06proto3"

var (
	file_samvaad_connector_proto_rawDescOnce sync.Once
	file_samvaad_connector_proto_rawDescData []byte
)

func file_samvaad_connector_proto_rawDescGZIP() []byte {
	file_samvaad_connector_proto_rawDescOnce.Do(func() {
		file_samvaad_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_samvaad_connector_proto_rawDesc), len(file_samvaad_connector_proto_rawDesc)))
	})
	return file_samvaad_connector_proto_rawDescData
}

var file_samvaad_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_samvaad_connector_proto_goTypes = []any{
	(ConnectorType)(0),                     // 0: samvaad.ConnectorType
	(*DialWhatsAppCallRequest)(nil),        // 1: samvaad.DialWhatsAppCallRequest
	(*DisconnectWhatsAppCallRequest)(nil),  // 2: samvaad.DisconnectWhatsAppCallRequest
	(*ConnectWhatsAppCallRequest)(nil),     // 3: samvaad.ConnectWhatsAppCallRequest
	(*AcceptWhatsAppCallRequest)(nil),      // 4: samvaad.AcceptWhatsAppCallRequest
	(*ConnectTwilioCallRequest)(nil),       // 5: samvaad.ConnectTwilioCallRequest
	(*DialWhatsAppCallResponse)(nil),       // 6: samvaad.DialWhatsAppCallResponse
	(*DisconnectWhatsAppCallResponse)(nil), // 7: samvaad.DisconnectWhatsAppCallResponse
	(*ConnectWhatsAppCallResponse)(nil),    // 8: samvaad.ConnectWhatsAppCallResponse
	(*AcceptWhatsAppCallResponse)(nil),     // 9: samvaad.AcceptWhatsAppCallResponse
	(*ConnectTwilioCallResponse)(nil),      // 10: samvaad.ConnectTwilioCallResponse
}
var file_samvaad_connector_proto_depIdxs = []int32{
	1,  // 0: samvaad.Connector.DialWhatsAppCall:input_type -> samvaad.DialWhatsAppCallRequest
	2,  // 1: samvaad.Connector.DisconnectWhatsAppCall:input_type -> samvaad.DisconnectWhatsAppCallRequest
	3,  // 2: samvaad.Connector.ConnectWhatsAppCall:input_type -> samvaad.ConnectWhatsAppCallRequest
	4,  // 3: samvaad.Connector.AcceptWhatsAppCall:input_type -> samvaad.AcceptWhatsAppCallRequest
	5,  // 4: samvaad.Connector.ConnectTwilioCall:input_type -> samvaad.ConnectTwilioCallRequest
	6,  // 5: samvaad.Connector.DialWhatsAppCall:output_type -> samvaad.DialWhatsAppCallResponse
	7,  // 6: samvaad.Connector.DisconnectWhatsAppCall:output_type -> samvaad.DisconnectWhatsAppCallResponse
	8,  // 7: samvaad.Connector.ConnectWhatsAppCall:output_type -> samvaad.ConnectWhatsAppCallResponse
	9,  // 8: samvaad.Connector.AcceptWhatsAppCall:output_type -> samvaad.AcceptWhatsAppCallResponse
	10, // 9: samvaad.Connector.ConnectTwilioCall:output_type -> samvaad.ConnectTwilioCallResponse
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_samvaad_connector_proto_init() }
func file_samvaad_connector_proto_init() {
	if File_samvaad_connector_proto != nil {
		return
	}
	file_samvaad_connector_whatsapp_proto_init()
	file_samvaad_connector_twilio_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_samvaad_connector_proto_rawDesc), len(file_samvaad_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_samvaad_connector_proto_goTypes,
		DependencyIndexes: file_samvaad_connector_proto_depIdxs,
		EnumInfos:         file_samvaad_connector_proto_enumTypes,
	}.Build()
	File_samvaad_connector_proto = out.File
	file_samvaad_connector_proto_goTypes = nil
	file_samvaad_connector_proto_depIdxs = nil
}
