// Copyright 2023 Samvaad, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: rpc/egress.proto

package rpc

import (
	samvaad "github.com/msmclass/samvaad/pkg/proto/samvaad"
	_ "github.com/msmclass/samvaad/pkg/proto/samvaad/logger"
	_ "github.com/msmclass/samvaad/pkg/samvaad/psrpc/protoc-gen-psrpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartEgressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request metadata
	EgressId string `protobuf:"bytes,1,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	// request
	//
	// Types that are valid to be assigned to Request:
	//
	//	*StartEgressRequest_Egress
	//	*StartEgressRequest_Replay
	//	*StartEgressRequest_RoomComposite
	//	*StartEgressRequest_Web
	//	*StartEgressRequest_Participant
	//	*StartEgressRequest_TrackComposite
	//	*StartEgressRequest_Track
	Request isStartEgressRequest_Request `protobuf_oneof:"request"`
	// connection info
	RoomId   string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName string `protobuf:"bytes,18,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token    string `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	WsUrl    string `protobuf:"bytes,9,opt,name=ws_url,json=wsUrl,proto3" json:"ws_url,omitempty"`
	// cloud only
	CloudBackupEnabled bool    `protobuf:"varint,10,opt,name=cloud_backup_enabled,json=cloudBackupEnabled,proto3" json:"cloud_backup_enabled,omitempty"`
	EstimatedCpu       float64 `protobuf:"fixed64,14,opt,name=estimated_cpu,json=estimatedCpu,proto3" json:"estimated_cpu,omitempty"`
	RetryCount         int32   `protobuf:"varint,15,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartEgressRequest) Reset() {
	*x = StartEgressRequest{}
	mi := &file_rpc_egress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEgressRequest) ProtoMessage() {}

func (x *StartEgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_egress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEgressRequest.ProtoReflect.Descriptor instead.
func (*StartEgressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_egress_proto_rawDescGZIP(), []int{0}
}

func (x *StartEgressRequest) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

func (x *StartEgressRequest) GetRequest() isStartEgressRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StartEgressRequest) GetEgress() *samvaad.StartEgressRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_Egress); ok {
			return x.Egress
		}
	}
	return nil
}

func (x *StartEgressRequest) GetReplay() *samvaad.ExportReplayRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

func (x *StartEgressRequest) GetRoomComposite() *samvaad.RoomCompositeEgressRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_RoomComposite); ok {
			return x.RoomComposite
		}
	}
	return nil
}

func (x *StartEgressRequest) GetWeb() *samvaad.WebEgressRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_Web); ok {
			return x.Web
		}
	}
	return nil
}

func (x *StartEgressRequest) GetParticipant() *samvaad.ParticipantEgressRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_Participant); ok {
			return x.Participant
		}
	}
	return nil
}

func (x *StartEgressRequest) GetTrackComposite() *samvaad.TrackCompositeEgressRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_TrackComposite); ok {
			return x.TrackComposite
		}
	}
	return nil
}

func (x *StartEgressRequest) GetTrack() *samvaad.TrackEgressRequest {
	if x != nil {
		if x, ok := x.Request.(*StartEgressRequest_Track); ok {
			return x.Track
		}
	}
	return nil
}

func (x *StartEgressRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartEgressRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *StartEgressRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StartEgressRequest) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

func (x *StartEgressRequest) GetCloudBackupEnabled() bool {
	if x != nil {
		return x.CloudBackupEnabled
	}
	return false
}

func (x *StartEgressRequest) GetEstimatedCpu() float64 {
	if x != nil {
		return x.EstimatedCpu
	}
	return 0
}

func (x *StartEgressRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type isStartEgressRequest_Request interface {
	isStartEgressRequest_Request()
}

type StartEgressRequest_Egress struct {
	Egress *samvaad.StartEgressRequest `protobuf:"bytes,16,opt,name=egress,proto3,oneof"`
}

type StartEgressRequest_Replay struct {
	Replay *samvaad.ExportReplayRequest `protobuf:"bytes,17,opt,name=replay,proto3,oneof"`
}

type StartEgressRequest_RoomComposite struct {
	// --- deprecated ---
	RoomComposite *samvaad.RoomCompositeEgressRequest `protobuf:"bytes,5,opt,name=room_composite,json=roomComposite,proto3,oneof"`
}

type StartEgressRequest_Web struct {
	Web *samvaad.WebEgressRequest `protobuf:"bytes,11,opt,name=web,proto3,oneof"`
}

type StartEgressRequest_Participant struct {
	Participant *samvaad.ParticipantEgressRequest `protobuf:"bytes,13,opt,name=participant,proto3,oneof"`
}

type StartEgressRequest_TrackComposite struct {
	TrackComposite *samvaad.TrackCompositeEgressRequest `protobuf:"bytes,6,opt,name=track_composite,json=trackComposite,proto3,oneof"`
}

type StartEgressRequest_Track struct {
	Track *samvaad.TrackEgressRequest `protobuf:"bytes,7,opt,name=track,proto3,oneof"`
}

func (*StartEgressRequest_Egress) isStartEgressRequest_Request() {}

func (*StartEgressRequest_Replay) isStartEgressRequest_Request() {}

func (*StartEgressRequest_RoomComposite) isStartEgressRequest_Request() {}

func (*StartEgressRequest_Web) isStartEgressRequest_Request() {}

func (*StartEgressRequest_Participant) isStartEgressRequest_Request() {}

func (*StartEgressRequest_TrackComposite) isStartEgressRequest_Request() {}

func (*StartEgressRequest_Track) isStartEgressRequest_Request() {}

type ListActiveEgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveEgressRequest) Reset() {
	*x = ListActiveEgressRequest{}
	mi := &file_rpc_egress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveEgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveEgressRequest) ProtoMessage() {}

func (x *ListActiveEgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_egress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveEgressRequest.ProtoReflect.Descriptor instead.
func (*ListActiveEgressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_egress_proto_rawDescGZIP(), []int{1}
}

type ListActiveEgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressIds     []string               `protobuf:"bytes,1,rep,name=egress_ids,json=egressIds,proto3" json:"egress_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveEgressResponse) Reset() {
	*x = ListActiveEgressResponse{}
	mi := &file_rpc_egress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveEgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveEgressResponse) ProtoMessage() {}

func (x *ListActiveEgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_egress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveEgressResponse.ProtoReflect.Descriptor instead.
func (*ListActiveEgressResponse) Descriptor() ([]byte, []int) {
	return file_rpc_egress_proto_rawDescGZIP(), []int{2}
}

func (x *ListActiveEgressResponse) GetEgressIds() []string {
	if x != nil {
		return x.EgressIds
	}
	return nil
}

type EgressReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EgressId      string                 `protobuf:"bytes,1,opt,name=egress_id,json=egressId,proto3" json:"egress_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressReadyRequest) Reset() {
	*x = EgressReadyRequest{}
	mi := &file_rpc_egress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressReadyRequest) ProtoMessage() {}

func (x *EgressReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_egress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressReadyRequest.ProtoReflect.Descriptor instead.
func (*EgressReadyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_egress_proto_rawDescGZIP(), []int{3}
}

func (x *EgressReadyRequest) GetEgressId() string {
	if x != nil {
		return x.EgressId
	}
	return ""
}

type EgressReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartAt       int64                  `protobuf:"varint,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`          // wallclock unix timestamp (nanoseconds)
	DurationMs    int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // how long to record
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressReadyResponse) Reset() {
	*x = EgressReadyResponse{}
	mi := &file_rpc_egress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressReadyResponse) ProtoMessage() {}

func (x *EgressReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_egress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressReadyResponse.ProtoReflect.Descriptor instead.
func (*EgressReadyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_egress_proto_rawDescGZIP(), []int{4}
}

func (x *EgressReadyResponse) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *EgressReadyResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_rpc_egress_proto protoreflect.FileDescriptor

const file_rpc_egress_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/egress.proto\x12\x03rpc\x1a\roptions.proto\x1a\x14logger/options.proto\x1a\x14\x6c\x69\x76\x65\x6b\x69\x74_egress.proto\"\xed\x05\n" +
	"\x12StartEgressRequest\x12(\n" +
	"\tegress_id\x18\x01 \x01(\tB\v\xbaP\begressIDR\begressId\x125\n" +
	"\x06egress\x18\x10 \x01(\v2\x1b.\x6c\x69\x76\x65\x6b\x69\x74.StartEgressRequestH\x00R\x06egress\x126\n" +
	"\x06replay\x18\x11 \x01(\v2\x1c.\x6c\x69\x76\x65\x6b\x69\x74.ExportReplayRequestH\x00R\x06replay\x12L\n" +
	"\x0eroom_composite\x18\x05 \x01(\v2#.\x6c\x69\x76\x65\x6b\x69\x74.RoomCompositeEgressRequestH\x00R\rroomComposite\x12-\n" +
	"\x03web\x18\v \x01(\v2\x19.\x6c\x69\x76\x65\x6b\x69\x74.WebEgressRequestH\x00R\x03web\x12E\n" +
	"\vparticipant\x18\r \x01(\v2!.\x6c\x69\x76\x65\x6b\x69\x74.ParticipantEgressRequestH\x00R\vparticipant\x12O\n" +
	"\x0ftrack_composite\x18\x06 \x01(\v2$.\x6c\x69\x76\x65\x6b\x69\x74.TrackCompositeEgressRequestH\x00R\x0etrackComposite\x123\n" +
	"\x05track\x18\a \x01(\v2\x1b.\x6c\x69\x76\x65\x6b\x69\x74.TrackEgressRequestH\x00R\x05track\x12\"\n" +
	"\aroom_id\x18\x03 \x01(\tB\t\xbaP\x06roomIDR\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x12 \x01(\tR\broomName\x12\x19\n" +
	"\x05token\x18\b \x01(\tB\x03\xa8P\x01R\x05token\x12\x15\n" +
	"\x06ws_url\x18\t \x01(\tR\x05wsUrl\x120\n" +
	"\x14cloud_backup_enabled\x18\n" +
	" \x01(\bR\x12cloudBackupEnabled\x12#\n" +
	"\restimated_cpu\x18\x0e \x01(\x01R\festimatedCpu\x12\x1f\n" +
	"\vretry_count\x18\x0f \x01(\x05R\n" +
	"retryCountB\t\n" +
	"\arequest\"\x19\n" +
	"\x17ListActiveEgressRequest\"9\n" +
	"\x18ListActiveEgressResponse\x12\x1d\n" +
	"\n" +
	"egress_ids\x18\x01 \x03(\tR\tegressIds\">\n" +
	"\x12EgressReadyRequest\x12(\n" +
	"\tegress_id\x18\x01 \x01(\tB\v\xbaP\begressIDR\begressId\"Q\n" +
	"\x13EgressReadyResponse\x12\x19\n" +
	"\bstart_at\x18\x01 \x01(\x03R\astartAt\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs2\xb2\x01\n" +
	"\x0eEgressInternal\x12E\n" +
	"\vStartEgress\x12\x17.rpc.StartEgressRequest\x1a\x13.\x6c\x69\x76\x65\x6b\x69\x74.EgressInfo\"\b\xb2\x89\x01\x04\x10\x010\x01\x12Y\n" +
	"\x10ListActiveEgress\x12\x1c.rpc.ListActiveEgressRequest\x1a\x1d.rpc.ListActiveEgressResponse\"\b\xb2\x89\x01\x04\x10\x01(\x012\xec\x01\n" +
	"\rEgressHandler\x12I\n" +
	"\fUpdateEgress\x12\x1c.\x6c\x69\x76\x65\x6b\x69\x74.UpdateEgressRequest\x1a\x13.\x6c\x69\x76\x65\x6b\x69\x74.EgressInfo\"\x06\xb2\x89\x01\x02\x10\x01\x12E\n" +
	"\n" +
	"StopEgress\x12\x1a.\x6c\x69\x76\x65\x6b\x69\x74.StopEgressRequest\x1a\x13.\x6c\x69\x76\x65\x6b\x69\x74.EgressInfo\"\x06\xb2\x89\x01\x02\x10\x01\x12I\n" +
	"\fUpdateStream\x12\x1c.\x6c\x69\x76\x65\x6b\x69\x74.UpdateStreamRequest\x1a\x13.\x6c\x69\x76\x65\x6b\x69\x74.EgressInfo\"\x06\xb2\x89\x01\x02\x10\x012\\\n" +
	"\fReplayExport\x12L\n" +
	"\vEgressReady\x12\x17.rpc.EgressReadyRequest\x1a\x18.rpc.EgressReadyResponse\"\n" +
	"\xb2\x89\x01\x06\x10\x01\x1a\x02 \x01B!Z\x1fgithub.com/\x6c\x69\x76\x65\x6b\x69\x74/protocol/rpcb\x06proto3"

var (
	file_rpc_egress_proto_rawDescOnce sync.Once
	file_rpc_egress_proto_rawDescData []byte
)

func file_rpc_egress_proto_rawDescGZIP() []byte {
	file_rpc_egress_proto_rawDescOnce.Do(func() {
		file_rpc_egress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_egress_proto_rawDesc), len(file_rpc_egress_proto_rawDesc)))
	})
	return file_rpc_egress_proto_rawDescData
}

var file_rpc_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_egress_proto_goTypes = []any{
	(*StartEgressRequest)(nil),                  // 0: rpc.StartEgressRequest
	(*ListActiveEgressRequest)(nil),             // 1: rpc.ListActiveEgressRequest
	(*ListActiveEgressResponse)(nil),            // 2: rpc.ListActiveEgressResponse
	(*EgressReadyRequest)(nil),                  // 3: rpc.EgressReadyRequest
	(*EgressReadyResponse)(nil),                 // 4: rpc.EgressReadyResponse
	(*samvaad.StartEgressRequest)(nil),          // 5: samvaad.StartEgressRequest
	(*samvaad.ExportReplayRequest)(nil),         // 6: samvaad.ExportReplayRequest
	(*samvaad.RoomCompositeEgressRequest)(nil),  // 7: samvaad.RoomCompositeEgressRequest
	(*samvaad.WebEgressRequest)(nil),            // 8: samvaad.WebEgressRequest
	(*samvaad.ParticipantEgressRequest)(nil),    // 9: samvaad.ParticipantEgressRequest
	(*samvaad.TrackCompositeEgressRequest)(nil), // 10: samvaad.TrackCompositeEgressRequest
	(*samvaad.TrackEgressRequest)(nil),          // 11: samvaad.TrackEgressRequest
	(*samvaad.UpdateEgressRequest)(nil),         // 12: samvaad.UpdateEgressRequest
	(*samvaad.StopEgressRequest)(nil),           // 13: samvaad.StopEgressRequest
	(*samvaad.UpdateStreamRequest)(nil),         // 14: samvaad.UpdateStreamRequest
	(*samvaad.EgressInfo)(nil),                  // 15: samvaad.EgressInfo
}
var file_rpc_egress_proto_depIdxs = []int32{
	5,  // 0: rpc.StartEgressRequest.egress:type_name -> samvaad.StartEgressRequest
	6,  // 1: rpc.StartEgressRequest.replay:type_name -> samvaad.ExportReplayRequest
	7,  // 2: rpc.StartEgressRequest.room_composite:type_name -> samvaad.RoomCompositeEgressRequest
	8,  // 3: rpc.StartEgressRequest.web:type_name -> samvaad.WebEgressRequest
	9,  // 4: rpc.StartEgressRequest.participant:type_name -> samvaad.ParticipantEgressRequest
	10, // 5: rpc.StartEgressRequest.track_composite:type_name -> samvaad.TrackCompositeEgressRequest
	11, // 6: rpc.StartEgressRequest.track:type_name -> samvaad.TrackEgressRequest
	0,  // 7: rpc.EgressInternal.StartEgress:input_type -> rpc.StartEgressRequest
	1,  // 8: rpc.EgressInternal.ListActiveEgress:input_type -> rpc.ListActiveEgressRequest
	12, // 9: rpc.EgressHandler.UpdateEgress:input_type -> samvaad.UpdateEgressRequest
	13, // 10: rpc.EgressHandler.StopEgress:input_type -> samvaad.StopEgressRequest
	14, // 11: rpc.EgressHandler.UpdateStream:input_type -> samvaad.UpdateStreamRequest
	3,  // 12: rpc.ReplayExport.EgressReady:input_type -> rpc.EgressReadyRequest
	15, // 13: rpc.EgressInternal.StartEgress:output_type -> samvaad.EgressInfo
	2,  // 14: rpc.EgressInternal.ListActiveEgress:output_type -> rpc.ListActiveEgressResponse
	15, // 15: rpc.EgressHandler.UpdateEgress:output_type -> samvaad.EgressInfo
	15, // 16: rpc.EgressHandler.StopEgress:output_type -> samvaad.EgressInfo
	15, // 17: rpc.EgressHandler.UpdateStream:output_type -> samvaad.EgressInfo
	4,  // 18: rpc.ReplayExport.EgressReady:output_type -> rpc.EgressReadyResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_egress_proto_init() }
func file_rpc_egress_proto_init() {
	if File_rpc_egress_proto != nil {
		return
	}
	file_rpc_egress_proto_msgTypes[0].OneofWrappers = []any{
		(*StartEgressRequest_Egress)(nil),
		(*StartEgressRequest_Replay)(nil),
		(*StartEgressRequest_RoomComposite)(nil),
		(*StartEgressRequest_Web)(nil),
		(*StartEgressRequest_Participant)(nil),
		(*StartEgressRequest_TrackComposite)(nil),
		(*StartEgressRequest_Track)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_egress_proto_rawDesc), len(file_rpc_egress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_rpc_egress_proto_goTypes,
		DependencyIndexes: file_rpc_egress_proto_depIdxs,
		MessageInfos:      file_rpc_egress_proto_msgTypes,
	}.Build()
	File_rpc_egress_proto = out.File
	file_rpc_egress_proto_goTypes = nil
	file_rpc_egress_proto_depIdxs = nil
}
