// Copyright 2023 Samvaad, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: rpc/participant.proto

package rpc

import (
	samvaad "github.com/msmclass/samvaad/pkg/proto/samvaad"
	_ "github.com/msmclass/samvaad/pkg/samvaad/psrpc/protoc-gen-psrpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_participant_proto protoreflect.FileDescriptor

const file_rpc_participant_proto_rawDesc = "" +
	"\n" +
	"\x15rpc/participant.proto\x12\x03rpc\x1a\roptions.proto\x1a\x14\x6c\x69\x76\x65\x6b\x69\x74_models.proto\x1a\x12\x6c\x69\x76\x65\x6b\x69\x74_room.proto2\xf9\x06\n" +
	"\vParticipant\x12\x7f\n" +
	"\x11RemoveParticipant\x12 .\x6c\x69\x76\x65\x6b\x69\x74.RoomParticipantIdentity\x1a\".\x6c\x69\x76\x65\x6b\x69\x74.RemoveParticipantResponse\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01\x12y\n" +
	"\x12MutePublishedTrack\x12\x1d.\x6c\x69\x76\x65\x6b\x69\x74.MuteRoomTrackRequest\x1a\x1e.\x6c\x69\x76\x65\x6b\x69\x74.MuteRoomTrackResponse\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01\x12v\n" +
	"\x11UpdateParticipant\x12!.\x6c\x69\x76\x65\x6b\x69\x74.UpdateParticipantRequest\x1a\x18.\x6c\x69\x76\x65\x6b\x69\x74.ParticipantInfo\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01\x12\x86\x01\n" +
	"\x13UpdateSubscriptions\x12#.\x6c\x69\x76\x65\x6b\x69\x74.UpdateSubscriptionsRequest\x1a$.\x6c\x69\x76\x65\x6b\x69\x74.UpdateSubscriptionsResponse\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01\x12\x83\x01\n" +
	"\x12ForwardParticipant\x12\".\x6c\x69\x76\x65\x6b\x69\x74.ForwardParticipantRequest\x1a#.\x6c\x69\x76\x65\x6b\x69\x74.ForwardParticipantResponse\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01\x12z\n" +
	"\x0fMoveParticipant\x12\x1f.\x6c\x69\x76\x65\x6b\x69\x74.MoveParticipantRequest\x1a .\x6c\x69\x76\x65\x6b\x69\x74.MoveParticipantResponse\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01\x12k\n" +
	"\n" +
	"PerformRpc\x12\x1a.\x6c\x69\x76\x65\x6b\x69\x74.PerformRpcRequest\x1a\x1b.\x6c\x69\x76\x65\x6b\x69\x74.PerformRpcResponse\"$\xb2\x89\x01 \x10\x01\x1a\x1c\n" +
	"\vparticipant\x12\vparticipant\x18\x01B!Z\x1fgithub.com/\x6c\x69\x76\x65\x6b\x69\x74/protocol/rpcb\x06proto3"

var file_rpc_participant_proto_goTypes = []any{
	(*samvaad.RoomParticipantIdentity)(nil),     // 0: samvaad.RoomParticipantIdentity
	(*samvaad.MuteRoomTrackRequest)(nil),        // 1: samvaad.MuteRoomTrackRequest
	(*samvaad.UpdateParticipantRequest)(nil),    // 2: samvaad.UpdateParticipantRequest
	(*samvaad.UpdateSubscriptionsRequest)(nil),  // 3: samvaad.UpdateSubscriptionsRequest
	(*samvaad.ForwardParticipantRequest)(nil),   // 4: samvaad.ForwardParticipantRequest
	(*samvaad.MoveParticipantRequest)(nil),      // 5: samvaad.MoveParticipantRequest
	(*samvaad.PerformRpcRequest)(nil),           // 6: samvaad.PerformRpcRequest
	(*samvaad.RemoveParticipantResponse)(nil),   // 7: samvaad.RemoveParticipantResponse
	(*samvaad.MuteRoomTrackResponse)(nil),       // 8: samvaad.MuteRoomTrackResponse
	(*samvaad.ParticipantInfo)(nil),             // 9: samvaad.ParticipantInfo
	(*samvaad.UpdateSubscriptionsResponse)(nil), // 10: samvaad.UpdateSubscriptionsResponse
	(*samvaad.ForwardParticipantResponse)(nil),  // 11: samvaad.ForwardParticipantResponse
	(*samvaad.MoveParticipantResponse)(nil),     // 12: samvaad.MoveParticipantResponse
	(*samvaad.PerformRpcResponse)(nil),          // 13: samvaad.PerformRpcResponse
}
var file_rpc_participant_proto_depIdxs = []int32{
	0,  // 0: rpc.Participant.RemoveParticipant:input_type -> samvaad.RoomParticipantIdentity
	1,  // 1: rpc.Participant.MutePublishedTrack:input_type -> samvaad.MuteRoomTrackRequest
	2,  // 2: rpc.Participant.UpdateParticipant:input_type -> samvaad.UpdateParticipantRequest
	3,  // 3: rpc.Participant.UpdateSubscriptions:input_type -> samvaad.UpdateSubscriptionsRequest
	4,  // 4: rpc.Participant.ForwardParticipant:input_type -> samvaad.ForwardParticipantRequest
	5,  // 5: rpc.Participant.MoveParticipant:input_type -> samvaad.MoveParticipantRequest
	6,  // 6: rpc.Participant.PerformRpc:input_type -> samvaad.PerformRpcRequest
	7,  // 7: rpc.Participant.RemoveParticipant:output_type -> samvaad.RemoveParticipantResponse
	8,  // 8: rpc.Participant.MutePublishedTrack:output_type -> samvaad.MuteRoomTrackResponse
	9,  // 9: rpc.Participant.UpdateParticipant:output_type -> samvaad.ParticipantInfo
	10, // 10: rpc.Participant.UpdateSubscriptions:output_type -> samvaad.UpdateSubscriptionsResponse
	11, // 11: rpc.Participant.ForwardParticipant:output_type -> samvaad.ForwardParticipantResponse
	12, // 12: rpc.Participant.MoveParticipant:output_type -> samvaad.MoveParticipantResponse
	13, // 13: rpc.Participant.PerformRpc:output_type -> samvaad.PerformRpcResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_participant_proto_init() }
func file_rpc_participant_proto_init() {
	if File_rpc_participant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_participant_proto_rawDesc), len(file_rpc_participant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_participant_proto_goTypes,
		DependencyIndexes: file_rpc_participant_proto_depIdxs,
	}.Build()
	File_rpc_participant_proto = out.File
	file_rpc_participant_proto_goTypes = nil
	file_rpc_participant_proto_depIdxs = nil
}
