// Copyright 2023 Samvaad, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: rpc/room.proto

package rpc

import (
	samvaad "github.com/msmclass/samvaad/pkg/proto/samvaad"
	_ "github.com/msmclass/samvaad/pkg/samvaad/psrpc/protoc-gen-psrpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_room_proto protoreflect.FileDescriptor

const file_rpc_room_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/room.proto\x12\x03rpc\x1a\roptions.proto\x1a\x14\x6c\x69\x76\x65\x6b\x69\x74_models.proto\x1a\x12\x6c\x69\x76\x65\x6b\x69\x74_room.proto2\xf6\x03\n" +
	"\x04Room\x12]\n" +
	"\n" +
	"DeleteRoom\x12\x1a.\x6c\x69\x76\x65\x6b\x69\x74.DeleteRoomRequest\x1a\x1b.\x6c\x69\x76\x65\x6b\x69\x74.DeleteRoomResponse\"\x16\xb2\x89\x01\x12\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01\x12W\n" +
	"\bSendData\x12\x18.\x6c\x69\x76\x65\x6b\x69\x74.SendDataRequest\x1a\x19.\x6c\x69\x76\x65\x6b\x69\x74.SendDataResponse\"\x16\xb2\x89\x01\x12\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01\x12_\n" +
	"\x12UpdateRoomMetadata\x12\".\x6c\x69\x76\x65\x6b\x69\x74.UpdateRoomMetadataRequest\x1a\r.\x6c\x69\x76\x65\x6b\x69\x74.Room\"\x16\xb2\x89\x01\x12\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01\x12o\n" +
	"\x10ListParticipants\x12 .\x6c\x69\x76\x65\x6b\x69\x74.ListParticipantsRequest\x1a!.\x6c\x69\x76\x65\x6b\x69\x74.ListParticipantsResponse\"\x16\xb2\x89\x01\x12\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01\x12d\n" +
	"\x0eGetParticipant\x12 .\x6c\x69\x76\x65\x6b\x69\x74.RoomParticipantIdentity\x1a\x18.\x6c\x69\x76\x65\x6b\x69\x74.ParticipantInfo\"\x16\xb2\x89\x01\x12\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01B!Z\x1fgithub.com/\x6c\x69\x76\x65\x6b\x69\x74/protocol/rpcb\x06proto3"

var file_rpc_room_proto_goTypes = []any{
	(*samvaad.DeleteRoomRequest)(nil),         // 0: samvaad.DeleteRoomRequest
	(*samvaad.SendDataRequest)(nil),           // 1: samvaad.SendDataRequest
	(*samvaad.UpdateRoomMetadataRequest)(nil), // 2: samvaad.UpdateRoomMetadataRequest
	(*samvaad.ListParticipantsRequest)(nil),   // 3: samvaad.ListParticipantsRequest
	(*samvaad.RoomParticipantIdentity)(nil),   // 4: samvaad.RoomParticipantIdentity
	(*samvaad.DeleteRoomResponse)(nil),        // 5: samvaad.DeleteRoomResponse
	(*samvaad.SendDataResponse)(nil),          // 6: samvaad.SendDataResponse
	(*samvaad.Room)(nil),                      // 7: samvaad.Room
	(*samvaad.ListParticipantsResponse)(nil),  // 8: samvaad.ListParticipantsResponse
	(*samvaad.ParticipantInfo)(nil),           // 9: samvaad.ParticipantInfo
}
var file_rpc_room_proto_depIdxs = []int32{
	0, // 0: rpc.Room.DeleteRoom:input_type -> samvaad.DeleteRoomRequest
	1, // 1: rpc.Room.SendData:input_type -> samvaad.SendDataRequest
	2, // 2: rpc.Room.UpdateRoomMetadata:input_type -> samvaad.UpdateRoomMetadataRequest
	3, // 3: rpc.Room.ListParticipants:input_type -> samvaad.ListParticipantsRequest
	4, // 4: rpc.Room.GetParticipant:input_type -> samvaad.RoomParticipantIdentity
	5, // 5: rpc.Room.DeleteRoom:output_type -> samvaad.DeleteRoomResponse
	6, // 6: rpc.Room.SendData:output_type -> samvaad.SendDataResponse
	7, // 7: rpc.Room.UpdateRoomMetadata:output_type -> samvaad.Room
	8, // 8: rpc.Room.ListParticipants:output_type -> samvaad.ListParticipantsResponse
	9, // 9: rpc.Room.GetParticipant:output_type -> samvaad.ParticipantInfo
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_room_proto_init() }
func file_rpc_room_proto_init() {
	if File_rpc_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_room_proto_rawDesc), len(file_rpc_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_room_proto_goTypes,
		DependencyIndexes: file_rpc_room_proto_depIdxs,
	}.Build()
	File_rpc_room_proto = out.File
	file_rpc_room_proto_goTypes = nil
	file_rpc_room_proto_depIdxs = nil
}
